
import {ManufacturerModel} from './ManufacturerModel';

export class VehiculeTypes {
    public cars: ManufacturerModel[] = [
        {value: "1", name: "אאודי"},
        {value: "2", name: "אברת'"},
        {value: "3", name: "אוטוביאנקי"},
        {value: "4", name: "אולדסמוביל"},
        {value: "5", name: "אוסטין"},
        {value: "6", name: "אופל"},
        {value: "7", name: "אינפיניטי"},
        {value: "8", name: "אל.טי.איי"},
        {value: "9", name: "אלפא רומיאו"},
        {value: "10", name: "אם. ג'י. / MG"},
        {value: "11", name: "אסטון מרטין"},
        {value: "12", name: "ב.מ.וו"},
        {value: "13", name: "ביואיק"},
        {value: "14", name: "בנטלי"},
        {value: "15", name: "ג'י.איי.סי/GAC"},
        {value: "16", name: "ג'יאו - Geo"},
        {value: "17", name: "ג'יפ / Jeep"},
        {value: "18", name: "גרייט וול"},
        {value: "19", name: "דאצ'יה"},
        {value: "20", name: "דודג'"},
        {value: "21", name: "די.אס / DS"},
        {value: "22", name: "דייהו"},
        {value: "23", name: "דייהטסו"},
        {value: "24", name: "הונדה"},
        {value: "25", name: "וולוו"},
        {value: "26", name: "טויוטה"},
        {value: "27", name: "טסלה"},
        {value: "28", name: "יגואר"},
        {value: "29", name: "יונדאי"},
        {value: "30", name: "לאדה"},
        {value: "31", name: "לינקולן"},
        {value: "32", name: "ליצ'י"},
        {value: "33", name: "למבורגיני"},
        {value: "34", name: "לנצ'יה"},
        {value: "35", name: "לקסוס"},
        {value: "36", name: "מאזדה"},
        {value: "37", name: "מזראטי"},
        {value: "38", name: "מיני"},
        {value: "39", name: "מיצובישי"},
        {value: "40", name: "מרצדס"},
        {value: "41", name: "ניסאן"},
        {value: "42", name: "ננג'ינג"},
        {value: "43", name: "סאאב"},
        {value: "44", name: "סאנגיונג"},
        {value: "45", name: "סאנשיין"},
        {value: "46", name: "סובארו"},
        {value: "47", name: "סוזוקי"},
        {value: "48", name: "סיאט"},
        {value: "49", name: "סיטרואן"},
        {value: "50", name: "סמארט"},
        {value: "51", name: "סקודה"},
        {value: "52", name: "פולקסווגן"},
        {value: "53", name: "פונטיאק"},
        {value: "54", name: "פורד"},
        {value: "55", name: "פורשה"},
        {value: "56", name: "פיאט"},
        {value: "57", name: "פיג'ו"},
        {value: "58", name: "פרארי"},
        {value: "59", name: "קאדילק"},
        {value: "60", name: "קיה"},
        {value: "61", name: "קרייזלר"},
        {value: "62", name: "רובר"},
        {value: "63", name: "רנו"},
        {value: "64", name: "שברולט"}
      ];
}