import  {Car} from '../interfaces/car'
export class VehiculeTypes {
    public cars: Car[] = [
        {value: "1", text: "אאודי"},
        {value: "227", text: "אברת'"},
        {value: "2", text: "אוטוביאנקי"},
        {value: "3", text: "אולדסמוביל"},
        {value: "4", text: "אוסטין"},
        {value: "5", text: "אופל"},
        {value: "195", text: "אינפיניטי"},
        {value: "264", text: "אל.טי.איי"},
        {value: "6", text: "אלפא רומיאו"},
        {value: "203", text: "אם. ג'י. / MG"},
        {value: "250", text: "אסטון מרטין"},
        {value: "7", text: "ב.מ.וו"},
        {value: "8", text: "ביואיק"},
        {value: "315", text: "בנטלי"},
        {value: "325", text: "ג'י.איי.סי/GAC"},
        {value: "10", text: "ג'יאו - Geo"},
        {value: "296", text: "ג'יפ / Jeep"},
        {value: "238", text: "גרייט וול"},
        {value: "255", text: "דאצ'יה"},
        {value: "11", text: "דודג'"},
        {value: "290", text: "די.אס / DS"},
        {value: "12", text: "דייהו"},
        {value: "13", text: "דייהטסו"},
        {value: "14", text: "הונדה"},
        {value: "15", text: "וולוו"},
        {value: "16", text: "טויוטה"},
        {value: "321", text: "טסלה"},
        {value: "18", text: "יגואר"},
        {value: "19", text: "יונדאי"},
        {value: "20", text: "לאדה"},
        {value: "156", text: "לינקולן"},
        {value: "297", text: "ליצ'י"},
        {value: "284", text: "למבורגיני"},
        {value: "21", text: "לנצ'יה"},
        {value: "163", text: "לקסוס"},
        {value: "22", text: "מאזדה"},
        {value: "224", text: "מזראטי"},
        {value: "187", text: "מיני"},
        {value: "23", text: "מיצובישי"},
        {value: "24", text: "מרצדס"},
        {value: "25", text: "ניסאן"},
        {value: "286", text: "ננג'ינג"},
        {value: "26", text: "סאאב"},
        {value: "278", text: "סאנגיונג"},
        {value: "319", text: "סאנשיין"},
        {value: "27", text: "סובארו"},
        {value: "28", text: "סוזוקי"},
        {value: "29", text: "סיאט"},
        {value: "30", text: "סיטרואן"},
        {value: "32", text: "סמארט"},
        {value: "31", text: "סקודה"},
        {value: "34", text: "פולקסווגן"},
        {value: "35", text: "פונטיאק"},
        {value: "36", text: "פורד"},
        {value: "37", text: "פורשה"},
        {value: "38", text: "פיאט"},
        {value: "33", text: "פיג'ו"},
        {value: "225", text: "פרארי"},
        {value: "39", text: "קאדילק"},
        {value: "40", text: "קיה"},
        {value: "41", text: "קרייזלר"},
        {value: "42", text: "רובר"},
        {value: "43", text: "רנו"},
        {value: "44", text: "שברולט"}
      ];
}