services:
  - type: web
    name: nuricar
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/WarningLightsApp
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html